### ISSUE TITLE
Possible typos in srpHash.cs: CreateHasher() method

### ISSUE THREAD

**Issue by dlandi** [secure-remote-password/srp.net#1]
Hi Yallie, 

During a code review of your code, I came across something that may be a typo in your choice of hashing algo:

![image](https://user-images.githubusercontent.com/3196088/44629567-49adb000-a91f-11e8-94c9-c5af7160eac0.png)

Btw, liking this library very much!

-dennis

**Comment by yallie** [comment]
Good catch! Thanks a lot :)
